CREATE TABLE IF NOT EXISTS endpoint_hits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app VARCHAR(255) NOT NULL,
    uri VARCHAR(512) NOT NULL,
    ip VARCHAR(15) NOT NULL,
    timestamp TIMESTAMP(0) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_endpoint_hits_timestamp ON endpoint_hits (timestamp);
CREATE INDEX IF NOT EXISTS idx_endpoint_hits_app_uri ON endpoint_hits (app, uri);
CREATE INDEX IF NOT EXISTS idx_endpoint_hits_ip_timestamp ON endpoint_hits (ip, timestamp);

COMMENT ON TABLE endpoint_hits IS 'Статистика запросов';
COMMENT ON COLUMN endpoint_hits.app IS 'Сервис';
COMMENT ON COLUMN endpoint_hits.uri IS 'Эндпоинт';
COMMENT ON COLUMN endpoint_hits.ip IS 'IP';
COMMENT ON COLUMN endpoint_hits.timestamp IS 'Время';